services:
  - type: web
    name: skin-ai-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11

